# Generated by Django 5.2.17 on 2026-09-09 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_operation_at', models.DateTimeField(blank=True, null=True)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_purchase_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('PROGRAM_RULES', 'PROGRAM_RULES'), ('PERSONAL_DATA', 'PERSONAL_DATA'), ('ADVERTISING', 'ADVERTISING')], max_length=50)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('revoked', 'revoked')], max_length=20)),
                ('accepted_at', models.DateTimeField()),
                ('text_version', models.CharField(max_length=50)),
                ('consent_text_hash', models.CharField(max_length=64)),
                ('telegram_id', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'consent_type', '-created_at'], name='clients_con_client__8a605b_idx')],
            },
        ),
    ]
