# Generated by Django 5.2.17 on 2026-09-09 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('accrual_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('max_redeem_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('earned_ttl_days', models.PositiveIntegerField(default=90)),
                ('gift_ttl_days', models.PositiveIntegerField(default=30)),
                ('registration_gift_points', models.PositiveIntegerField(default=500)),
                ('birthday_gift_points', models.PositiveIntegerField(default=1000)),
                ('birthday_message_template', models.TextField(default='Поздравляем с днём рождения! Вам начислены подарочные баллы.')),
                ('rules_text', models.TextField(blank=True, default='')),
                ('promotions_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_telegram_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BONUS_ACCRUAL', 'Bonus Accrual'), ('BONUS_REDEMPTION', 'Bonus Redemption'), ('GIFT_ACCRUAL', 'Gift Accrual'), ('BONUS_EXPIRATION', 'Bonus Expiration'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('REGISTRATION_GIFT', 'Registration Gift'), ('BIRTHDAY_GIFT', 'Birthday Gift')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('points', models.IntegerField()),
                ('point_type', models.CharField(blank=True, choices=[('earned', 'Earned'), ('gift', 'Gift'), ('mixed', 'Mixed')], max_length=20, null=True)),
                ('store_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('store_address_snapshot', models.CharField(blank=True, default='', max_length=500)),
                ('operator_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('override_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='clients.client')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='BonusLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point_type', models.CharField(choices=[('earned', 'Earned'), ('gift', 'Gift')], max_length=20)),
                ('initial_points', models.PositiveIntegerField()),
                ('remaining_points', models.PositiveIntegerField()),
                ('accrued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='clients.client')),
                ('source_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='loyalty.operation')),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_grants', to='clients.client')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLotAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='loyalty.bonuslot')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='loyalty.operation')),
            ],
        ),
        migrations.AddIndex(
            model_name='bonuslot',
            index=models.Index(fields=['client', 'expires_at', 'accrued_at', 'id'], name='loyalty_bon_client__631885_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='birthdaygrant',
            unique_together={('client', 'year')},
        ),
    ]
