# Generated by Django 5.2.17 on 2026-09-09 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('loyalty', '0002_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='loyalty.broadcast')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['broadcast', 'status'], name='loyalty_bro_broadca_1bd4aa_idx')],
                'unique_together': {('broadcast', 'client')},
            },
        ),
    ]
