# Generated by Django 5.2.17 on 2026-09-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_expiry_warning_operator_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bonuslot',
            new_name='loyalty_bon_is_expi_04aa1b_idx',
            old_name='loyalty_bon_is_expi_7c1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='profilechangerequest',
            new_name='loyalty_pro_status_365b2a_idx',
            old_name='loyalty_pro_status_7f2a1c_idx',
        ),
    ]
